version: "3"

services:
  node:
    image: node:10
    user: node
    working_dir: /home/node/app
    env_file: ./.env
    environment:
      - NODE_ENV=$NODE_ENV
    volumes:
      - ./front-end:/home/node/app
    restart: always
    ports:
      - "80:3000"
    expose:
      - "3000"
    command: bash -c "npm i && npm run build && npm start -p 3000"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: ./.env

  wordpress:
    build: .
    depends_on:
      - db
    command: bash -c 'install_wordpress && apache2-foreground'
    ports:
      - "8000:8000"
    restart: always
    env_file: ./.env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress

volumes:
  db_data: {}
